### ISSUE TITLE
Support for JSON decoding

### ISSUE THREAD

**Issue by pschichtel** [kluctl/template-controller#160]
I'm currently trying to use this operator to transform COSI bucket secrets into something certain applications support. COSI's secrets have 1 key called `BucketInfo`, which contains a JSON string with all the details on how to use the bucket. Problem is that most applications accept the details as separate environment variables or a custom configuration file or so.

This operator seemed like a good fit, but unfortunately the jinja template engine as configured in this project doesn't support decoding JSON.

**Comment by pschichtel** [comment]
I was also quite surprised to learn that jinja is behind the templates, since the examples I've seen on the website are quite similar to go's template syntax. in fact, having go's templates with sprig available as an option for templating would be kinda nice.

**Comment by codablock** [comment]
Hey, I can give a more detailed answer in the next days as I'm on the road. Did you check https://kluctl.io/docs/kluctl/templating/filters/? "from_yaml" is what you're looking for, as json is perfectly parsable by all yaml parsers.

**Comment by pschichtel** [comment]
ohh, I did try from_json, which I've found on a couple of sites, but I didn't consider that there could be from_yaml. Yeah that works as you'd expect. You can close this if you want.

**Comment by pschichtel** [comment]
since you have the zalando postgres operator example on the website, here is how I transform a COSI secret into a secret that can be used for environment variables to be used for patroni's WAL-E setup:

```yaml
apiVersion: templates.kluctl.io/v1alpha1
kind: ObjectTemplate
metadata:
  name: object-transformer
spec:
  serviceAccountName: object-transformer
  prune: true
  matrix:
    - name: backupBucket
      object:
        ref:
          apiVersion: v1
          kind: Secret
          name: backup-bucket
  templates:
  - object:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "transformed-backup-bucket"
      stringData:
        endpoint: "{{ (matrix.backupBucket.data.BucketInfo | b64decode | from_yaml).spec.secretS3.endpoint }}"
        waleEndpoint: '{{ (matrix.backupBucket.data.BucketInfo | b64decode | from_yaml).spec.secretS3.endpoint | replace("http://","http+path://") | replace("https://","https+path://") }}'
        bucket: "{{ (matrix.backupBucket.data.BucketInfo | b64decode | from_yaml).spec.bucketName }}"
        accessKey: "{{ (matrix.backupBucket.data.BucketInfo | b64decode | from_yaml).spec.secretS3.accessKeyID }}"
        secretKey: "{{ (matrix.backupBucket.data.BucketInfo | b64decode | from_yaml).spec.secretS3.accessSecretKey }}"
```
