### ISSUE TITLE
Utilise impersonation when watching resources

### ISSUE THREAD

**Issue by wwentland** [kluctl/template-controller#38]
# Overview

It would be fantastic if the template-controller could impersonate the relevant service accounts when setting up watches for resources referenced in an `ObjectTemplate`.

# Details

When setting up an `ObjectTemplate` that references a Cluster API resource as input, I created a service account and RBAC similar to:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: foocluster-transformer
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: foocluster-transformer
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["foo-connection"]
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups: ["infrastructure.cluster.x-k8s.io"]
    resources: ["foocluster"]
    resourceNames: ["foo"]
    verbs:
      - get
      - list
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: foocluster-transformer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: foocluster-transformer
subjects:
  - kind: ServiceAccount
    name: foocluster-transformer
    namespace: default
``` 

Due to template-controller's fantastic impersonation functionality, this allows me to define minimal access to relevant resources. With this in place, I am - however - seeing errors similar to the following:

```
E0518 13:54:05.679980       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.1/tools/cache/reflector.go:231: Failed to watch infrastructure.cluster.x-k8s.io/v1beta1, Kind=FooCluster: failed to list infrastructure.cluster.x-k8s.io/v1beta1, Kind=FooCluster: fooclusters.infrastructure.cluster.x-k8s.io is forbidden: User "system:serviceaccount:kluctl-system:template-controller" cannot list resource "fooclusters" in API group "infrastructure.cluster.x-k8s.io" at the cluster scope
``` 

It appears as if a new watch is configured for relevant resources which use the service account of the template-controller itself, rather than the specific one that allows access to these resources.

My assumption would be that all functionality that requires the watch (i.e. updates/changes) is broken and this also makes it hard to monitor for legitimate errors.
