### ISSUE TITLE
Matrix String Object = null

### ISSUE THREAD

**Issue by corinz** [kluctl/template-controller#39]
Hello, first off thank you for this project. It is truly wonderful. We are trying to roll it out, but having some issues and wondering if someone can help with this...

Basically, kluctl doesn't seem to resolve my secret reference properly, and it renders a blank or null value.

Here is my object template:
```
apiVersion: templates.kluctl.io/v1alpha1
kind: ObjectTemplate
metadata:
  name: pr-preview
  namespace: kluctl-system
spec:
  serviceAccountName: template-controller
  prune: true
  matrix:
    - name: pr
      object:
        ref:
          apiVersion: templates.kluctl.io/v1alpha1
          kind: ListGithubPullRequests
          name: pr-listener
        jsonPath: status.pullRequests
        expandLists: true
    - name: graphql
      object:
        ref:
          apiVersion: v1
          kind: Secret
          name: graphql
          namespace: kluctl-system
  templates:
....
```
I am then using `"{{ matrix.graphql.data.MY_KEY}}"` to set an environment var. When the object is deployed it has no value. i.e. in the kube deployment manifest it just says this without any `value:` key.
```
env:
  - name: MY_VAR
```
I know that the controller is picking up the secret because, when the secret does not exist in the kluctl-system namespace, I get an error message in the ObjectTemplate status. So I know it's finding it.

I would greatly appreciate your help. This is my last day to get this tech working!
