### ISSUE TITLE
GitProjector from tags not working

### ISSUE THREAD

**Issue by mtthwcmpbll** [kluctl/template-controller#78]
I've been experimenting with the GitProjector and ObjectTemplate based on the examples in the launch blog post in order to create new environments for specific commits based on git tags.  I've been able to successfully get the example working with `spec/ref/branch: ...` but when switching over to tags (`spec/ref/tag`) reconciliation fails with an error.

My GitProjector:
```yaml
apiVersion: templates.kluctl.io/v1alpha1
kind: GitProjector
metadata:
  name: environment-projector
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@bitbucket.org/my/repo.git
  secretRef:
    name: repo-secret
  ref:
    tag: PR-(\d)+
```

After this has been pushed to the cluster, I don't see any errors in the template-controller pod but I do see this error on the GitProjector itself:

```yaml
Status:
  Conditions:
    Last Transition Time:  2024-02-02T17:39:37Z
    Message:               could not determine ref type for refs/tags/PR-1444
    Observed Generation:   1
    Reason:                Error
    Status:                False
    Type:                  Ready   
```

I expected something similar to the using branch, being able to pull the value in my ObjectTemplate with `{{ matrix.git.ref.tag }}`.

I've been digging through the source code for that error string "could not determine ref type" and it looks like maybe the tags check should be checking for `hasPrefix(...)` similar to the branch logic above, but [is instead checking `hasSuffix(...)` instead](https://github.com/kluctl/template-controller/blob/534f1a499b8a228fe28b943cd59c78d5488fef88/controllers/gitprojector_controller.go#L227).

**Other details of my environment:**

My git repository is hosted in Bitbucket (which is why I'm using the normal GitProjector and tags for discovering pull requests, instead of something like `ListGithubPullRequests`.  I'm also deploying all of this using FluxCD, so Flux deploys the GitProjector and ObjectTemplate.  The GitProjector is looking at my application repository though, not the FluxCD config repo.
