### ISSUE TITLE
ability to use list of objects in objecttemplate

### ISSUE THREAD

**Issue by elee1766** [kluctl/template-controller#84]
it would be very useful if i could do something like 
```
matrix:
- name: input1
  objects:
    matches:
      apiVersion: v1
      kind: SomeResource
      namespace: default
      selector:
        "some/label": "yay"
```

the reason is - i would like to use a template combined with my own crd to deploy sets of resources. the template-operator in this way can act like a generic operator, which is very cool.
